### ISSUE TITLE
Tables with ODP rendering

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#1193]
## Render Original Data Points in table 1a and 1b
<img width="1056" alt="Screenshot 2022-03-09 at 11 12 37" src="https://user-images.githubusercontent.com/1138156/157420772-0c95d83b-7e6a-4eb4-9ef3-3a1c2b51bf01.png">

## Task list 
- [x] Create View assessment_fra_2020.original_data_point_data (see note 1)
- [x] If table is odp, then fetch original data points and them to store/pages/assessmentSection (see note 2)
- [x] In DataTable, get the years by merging years from ODP data and table data to render columns
- [x] Render Original data point data with link to header 

#### 1. Original data point data view 
```sql
-- ######## ORIGINAL DATA POINT
create or replace view assessment_fra_2020.original_data_point_data as
with classes as (
    select o.country_iso, o.year, jsonb_array_elements(o.national_classes) as class
    from assessment_fra_2020.original_data_point o
)
select c.country_iso,
       c.year,
--        c.class ->> 'area'                                                     as area,
       sum((c.class ->> 'area')::numeric * (c.class ->> 'forestPercent')::numeric / 100) as forest,
       sum((c.class ->> 'area')::numeric *
           (c.class ->> 'otherWoodedLandPercent')::numeric / 100)                        as other_wooded_land,
--        sum((c.class ->> 'area')::numeric *
--            (
--                    100 - coalesce(c.class ->> 'forestPercent', '0')::numeric -
--                    coalesce(c.class ->> 'otherWoodedLandPercent', '0')::numeric
--                ) / 100)                                                                  as other_land
       sum(
                       ((c.class ->> 'area')::numeric * (c.class ->> 'forestPercent')::numeric / 100) * -- forest
                       (c.class ->> 'forestNaturalPercent')::numeric / 100
           )                                                                             as natural_forest_area,
       sum(
                       ((c.class ->> 'area')::numeric * (c.class ->> 'forestPercent')::numeric / 100) * -- forest
                       (c.class ->> 'forestPlantationPercent')::numeric / 100
           )                                                                             as plantation_forest_area,
       sum(
                       (
                                   ((c.class ->> 'area')::numeric * (c.class ->> 'forestPercent')::numeric / 100) *
                                   (c.class ->> 'forestPlantationPercent')::numeric / 100
                           ) -- plantation_forest_area
                       *
                       (c.class ->> 'forestPlantationIntroducedPercent')::numeric / 100
           )                                                                             as plantation_forest_introduced_area,
       sum(
                       ((c.class ->> 'area')::numeric * (c.class ->> 'forestPercent')::numeric / 100) * -- forest
                       (c.class ->> 'otherPlantedForestPercent')::numeric / 100
           )                                                                             as other_planted_forest_area,
       sum(
                       ((c.class ->> 'area')::numeric * (c.class ->> 'forestPercent')::numeric / 100) * -- forest
                       (c.class ->> 'forestPlantationPercent')::numeric / 100
           ) -- plantation_forest_area
           +
       sum(
                       ((c.class ->> 'area')::numeric * (c.class ->> 'forestPercent')::numeric / 100) * -- forest
                       (c.class ->> 'otherPlantedForestPercent')::numeric / 100
           ) -- other_planted_forest_area

                                                                                         as planted_forest,

       (
           sum(
                           ((c.class ->> 'area')::numeric * (c.class ->> 'forestPercent')::numeric / 100) * -- forest
                           (c.class ->> 'forestNaturalPercent')::numeric / 100
               ) -- natural_forest_area
           )
           +
       (
               sum(
                               ((c.class ->> 'area')::numeric * (c.class ->> 'forestPercent')::numeric /
                                100) * -- forest
                               (c.class ->> 'forestPlantationPercent')::numeric / 100
                   ) -- plantation_forest_area
               +
               sum(
                               ((c.class ->> 'area')::numeric * (c.class ->> 'forestPercent')::numeric /
                                100) * -- forest
                               (c.class ->> 'otherPlantedForestPercent')::numeric / 100
                   ) -- other_planted_forest_area
           ) -- planted_forest
                                                                                         as total

from classes c
group by c.country_iso, c.year
order by c.country_iso, c.year;
```

#### 2. Select query to read original data point values
```sql
with data as (
    select o.country_iso,
           jsonb_object_agg(
                   o.year,
                   json_build_object(
                           'forest', json_build_object('raw', o.forest::varchar),
                           'other_wooded_land', json_build_object('raw', o.other_wooded_land::varchar),
                           'natural_forest_area', json_build_object('raw', o.natural_forest_area::varchar),
                           'plantation_forest_area', json_build_object('raw', o.plantation_forest_area::varchar),
                           'plantation_forest_introduced_area',
                           json_build_object('raw', o.plantation_forest_introduced_area::varchar),
                           'other_planted_forest_area', json_build_object('raw', o.other_planted_forest_area::varchar),
                           'planted_forest', json_build_object('raw', o.planted_forest::varchar),
                           'total', json_build_object('raw', o.total::varchar)
                       )
               ) as values
    from assessment_fra_2020.original_data_point_data o
    where o.country_iso = 'FIN'
    group by o.country_iso
)
select jsonb_object_agg(d.country_iso, json_build_object('original_data_point_value', d.values)) as data
from data d
group by d.country_iso;
```
