### ISSUE TITLE
TableData: Index by CountryIso->TableName->ColName->VariableName

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#1199]
## Task List

- [x] Update data views (see note 1)
- [x] Update BE getTableData (see note 2)
- [x] Update FE using new dataformat

#### 1 Data views
In tools/dataMigration/migrateData/_createDataViews.ts 
Use the following sql to generate data views:
```sql
create or replace view assessment_fra_2020.extentofforest as
(
select n.country_iso,
       r.props ->> 'variableName' as variable_name,
       c.props ->> 'colName'      as col_name,
       n.value
from assessment_fra_2020.node n
         left join assessment_fra.row r
                   on r.uuid = n.row_uuid
         left join assessment_fra.col c
                   on c.uuid = n.col_uuid
         left join assessment_fra."table" t
                   on t.id = r.table_id
where t.props ->> 'name' = 'extentOfForest'
  and r.props ->> 'type' in ('data', 'calculated')
order by 1, 2, 3
    );
```

#### 2 TableDataRepository getTableData
```sql
with agg1 as (
    select e.country_iso,
           'extentOfForest' as table_name,
           e.col_name,
           jsonb_object_agg(e.variable_name, e.value) as data
    from assessment_fra_2020.extentofforest e
    where e.country_iso in ('FIN')
    -- TODO: ADD where condition for variable  and columns
    group by 1, 2, 3
    -- TODO: Add union for multiple tables
),
     agg2 as (
         select a.country_iso,
                a.table_name,
                jsonb_object_agg(a.col_name, a.data) as data
         from agg1 a
         group by 1, 2
     ),
     agg3 as (
         select a.country_iso,
                jsonb_object_agg(a.table_name, a.data) as data
         from agg2 a
         group by 1
     )
select jsonb_object_agg(a.country_iso, a.data) as data
from agg3 a;

```
