### ISSUE TITLE
Persist and Visualize Estimation method applied 

### ISSUE THREAD

**Issue by pengchenglai** [openforis/fra-platform#2604]
#### Part 1 (Persist Estimation method parameters: Backend)  ( @minotogna )
- [x] when estimating values, persist in a new table node_values_estimation (id, uuid, props:{type,parmas...}) (to check table format) estimation applied. + add an entry to the activity log of type 'nodeEstimationApplied' with target the created nodeValuesEstimation .
- [x] when marking node as estimated, add to node value prop estimationUuid.

#### Part 2 (Visualize Estimation method  applied: Frontend) ( @rfontanarosa )
- [x] in ui, to cell which node values have an estimationUuid, add on top right a squared box with letter E inside.
- [x] on data table effect, fetch estimation if a node is encountered with an estimationUuid
- [x] when hovering E box, show tooltip with estimation information applied (add loader within tooltip if server still fetching) 

#### Part 3 (Show estimated cell invalid: Backend/Frontend)
Objective: An estimated cell must be 'invalidated' if an ODP has been updated after estimation was applied
Note: last edit odp timestamp must concern only and only values (not other metadata information)
- [x] UI/BE: on Datatable effect, and table has odp, add endpoint and fetch lastOdpEditTime, or add last edit time to odp already fetched?
- [x] UI: when a cell is estimated and estimation engine has been applied before last odp edit timestamp, on the left of box E, add warning icon (orange) with tooltip: `This value might not longer be consistent with the estimation method applied. One or original data point has changed after estimation.`

_________________________________________________________________________________________________________________________ 

**Original Issue:**

@minotogna 
New values estimated by estimation methods such as linear, repeat last or annual change should be highlighted.

Without estimation(how it looks like):
<img width="738" alt="1" src="https://github.com/openforis/fra-platform/assets/99216009/b398d80f-d83c-4821-90ba-37b562d48c10">

 The cell values using estimation method should be highlighted:
<img width="798" alt="2" src="https://github.com/openforis/fra-platform/assets/99216009/00ceb197-3d58-4751-91ac-b0f6e1db714d">

**Comment by pengchenglai** [comment]
One possible idea could be to put the capital letter of the method in the corner of the cell as an example of using _Repeat last_ below:
<img width="798" alt="3" src="https://github.com/openforis/fra-platform/assets/99216009/6d818b6e-66b4-4942-ac76-f351937c1b1e">

Or any other way if feasible and suitable.

**Comment by minotogna** [comment]
@pengchenglai thank you, updating description and title with some technicality
