### ISSUE TITLE
Measures/Dimensions/system of measurements + table/row/col/cell

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#4144]
## TODO

- [ ] Meta + DB Definition
- [ ] FRA Migration
- [ ] PanEuropean Migration
- [ ] BE: Metadata cache generation
- [ ] BE: Fetch assessments/metadata
- [ ] UI: Render DataTable (without ODP) refactor
- [ ] UI: Render DataTable with ODP 
- [ ] BE: Update nodes (w/o dependencies job)
- [ ] BE: Update nodes dependencies job
- [ ] UI: Update nodes
- [ ] UI: Estimates nodes
- [ ] UI: Data export

### Schema: public

**SystemOfMeasurement / Unit**
```typescript
export type SystemOfMeasurement = {
  baseUnitUUID: UUID // db
  name: string
  rules: {
    conversionFactor: Record<UUID, number> // conversion factor of each unit in relation to base unit
  }
  uuid: UUID
}

export type Unit = {
  name: string
  systemOfMeasurementUUIDs: Array<UUID> // a unit can belong to several system of units of measurement
  uuid: UUID
}
```

```typescript
/**
 * DB TABLES
 * ==== system_of_measurement
 * id,uuid,base_unit_uuid,name (unique),
 *
 * * ==== system_of_measurement_conversion_factor
 * id,system_of_measurement_uuid,unit_uuid
 *
 * ==== unit
 * id,uuid,name(unique)
 *
 * ==== unit_system_of_measurement
 * id,system_of_measurement_uuid,unit_uuid
 *
 */
```

```typescript
// ==== sample
export const area: SystemOfMeasurement = {
  baseUnitUUID: '',
  name: 'area',
  rules: { conversionFactor: {} },
  uuid: UUIDs.v4(),
}

export const haThousand: Unit = { name: 'haThousand', systemOfMeasurementUUIDs: [area.uuid], uuid: UUIDs.v4() }
export const ha: Unit = { name: 'ha', systemOfMeasurementUUIDs: [area.uuid], uuid: UUIDs.v4() }
export const kmSq: Unit = { name: 'kmSq', systemOfMeasurementUUIDs: [area.uuid], uuid: UUIDs.v4() }
export const mileSq: Unit = { name: 'mileSq', systemOfMeasurementUUIDs: [area.uuid], uuid: UUIDs.v4() }
export const acre1000: Unit = { name: 'acre1000', systemOfMeasurementUUIDs: [area.uuid], uuid: UUIDs.v4() }
export const acre: Unit = { name: 'acre', systemOfMeasurementUUIDs: [area.uuid], uuid: UUIDs.v4() }
export const haMillion: Unit = { name: 'haMillion', systemOfMeasurementUUIDs: [area.uuid], uuid: UUIDs.v4() }

area.baseUnitUUID = haThousand.uuid
area.rules.conversionFactor = {
  [area.baseUnitUUID]: 1,
  [ha.uuid]: 1000,
  [kmSq.uuid]: 10,
  [mileSq.uuid]: 3.86102,
  [acre1000.uuid]: 2.47105,
  [acre.uuid]: 2471.05,
  [haMillion.uuid]: 0.001,
}
// ==== end sample
```

**Category / Dimension / Measure**
```typescript
export type Category = {
  dimensions?: Array<Dimension> // not db column - lazy loaded
  name: string
  uuid: UUID
}
```

```typescript
// TODO: Should Dimension have a value? (e.g. value for numerical columns like 1990 - name='1990',value=1990) useful?
export type Dimension = {
  categoryUUIDs: Array<UUID>
  name: string
  uuid: UUID
}
```

```typescript
/**
 * DB TABLES
 * ==== category
 * id,uuid,name (unique),
 *
 * * ==== dimension
 * id,uuid,name (unique),
 *
 * ==== category_dimension
 * id,category_uuid,dimension_uuid
 *
 */
```

```typescript
export enum MeasureType {
  // TODO: Question (decimal and integer)
  decimal = 'decimal',
  integer = 'integer',
  // TODO: OR only number - and handle input mode decimal/integer)
  number = 'number',

  // AND text
  text = 'text',
}

export type Measure = {
  name: string
  type: MeasureType
  unitUUID: UUID
  uuid: UUID
}
```

### Schema: assessment_cycle

**Observation**
```typescript
export type Observation = {
  countryIso: CountryIso
  dimensionUUID: UUID
  measureUUID: UUID
  unitUUID: UUID
  uuid: UUID
  value: NodeValue
}
```

**AxisItem = Col | Row / Cell**

```typescript
// AxisItem = Col | Row
type AxisItem = {
  props: {
    dimensionUUID?: UUID // can be used in design mode to link a dimension to a specific (col or row)
    index: number
    measureUUID?: UUID // can be used in design mode to link a measure to a specific (col or row)
  }
  tableUUID: UUID
  uuid: UUID
}

export type Col = AxisItem

export type Row = AxisItem & {
  cells: Array<Cell> // added in repository getters
}
```

```typescript
//= ==== (ex Col)
export type Cell = {
  rowUUID: UUID
  uuid: UUID
  props: {
    // colName?: removed
    // colType: removed

    // ==== COMMON props
    classNames?: Record<CycleUuid, Array<string>> // TODO: Check what and where it's used
    index: number // migrate from number|string(header)
    style?: Record<CycleUuid, ColStyle> // TODO: Check what it's used (colSpan,rowSpan and ?)
    type: 'text|label' | 'observation' // TODO: Check where colType placeholder is used

    // ====  EITHER labels
    labels?: Record<CycleUuid, Label>

    // ==== OR
    calculateFn?: Record<CycleUuid, string>
    dimensionUUID?: UUID // new
    inputPlaceholder?: string
    linkedNodes?: Record<CycleUuid, ColLinkedNode> // TODO: Check - can we use calculateFn instead?
    measureUUID?: UUID // new
    multiline?: boolean // new: ex colType textarea
    readonly?: boolean
    select?: Record<CycleUuid, ColSelectProps> // ex colType select
    validateFns?: Record<CycleUuid, Array<string>>
    variableNo?: Record<CycleUuid, string> // TODO: Check where it's used
  }
}
```
