### ISSUE TITLE
ODP Refactor

### ISSUE THREAD

**Issue by minotogna** [openforis/fra-platform#943]
ODP Must be refactor so that the concept of draft/actual is removed and the ODP data is stored in a jsonb column.

### Part 1 - DB (@minotogna)
- [x] update odp Table: should have columns : id, country_iso, data 
- [x] create script to migrate current data
- [x] create odp_view (now ndp_view)
- [x] use odp_view where previously was used ndp_view
- [x] update extent_of_forest_view and forest_characteristics_view
- [x] update audit table with odpIdLegacy and new odpId

### Part 2 - Code
- create api get/post/patch/delete (@sorja)
  - [x] get
  - [x] post
  - [x] patch
  - [x] delete
- [x] insert into audit table (delete/update/create) (@sorja )
- UI integration
  - [x] get (@minotogna )
  - [x] post (@sorja )
  - [x] delete (@sorja )
  -  patch 
      - [x] rtk setup (@minotogna )
      - [x] Year (@minotogna )
      - [x] Data Sources (@minotogna )
      - [x] Classifications and definitions
      - [x] Original data and reclassification (1a)
      - [x] Original data and reclassification (1b)
      - [x] Verify copy paste works
      - [x] move @webapp/sectionSpec/fra/originalDataPoint/paste(@minotogna  )
  - [x] ensure recent activity section (home) works (@sorja )
  - [x] OriginalDataPoint/YearSelection fetch reserved years on mount (@sorja )
  - [x] Remove Cancel draft (remove cancel draft / mark as actual) (@minotogna )
  - [x] Remove OriginalDataListView (@sorja )
  - Actions to move to OriginalDataPointActions 
    - [x] NationalClass --> copyPreviousNationalClasses (@sorja ) (this requires also backend route and service update)
    - [x] webapp/components/Assessment/FraPrint/useFraPrintDataFetch.ts --> fetchOdps (@minotogna  )
- [x] update table 1a/1b api get data (@minotogna)
- [x] update data export (@minotogna )
- [x] Estimation engine (@minotogna)
- [x] remove OdpService/OdpRepository (@minotogna  )
